version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/file-handling.jar
  discard-paths: yes