cloud:
  aws:
    credentials:
      access-key: AKIATXIDYW2JKCCHWO5U
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: fileuploadbucketbyziahaider


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090